### ISSUE TITLE
send tx error

### ISSUE THREAD

**Issue by Sayplaydiv** [pokt-network/pocket-js-LEGACY#438]
const fromAccountPK = Buffer.from("xxxxxxx", "hex");
    const passphrase = "xxxxx";

// 1. Import the sender's account into the Pocket instance.
    let account = await pocketInstance.keybase.importAccount(fromAccountPK, passphrase)
// 2. Create a Transaction sender.
    let transactionSender = await pocketInstance.withImportedAccount(account.addressHex, passphrase)
    const fee = "10000";
    const balanceToSend = "100000";
    const chainID = "mainnet"
    let rawTxResponse = await transactionSender
        .send(account.addressHex, "590eb20e357158895d306d3c278e23144381a0b5", balanceToSend)
        .submit(chainID, fee)

**Comment by Sayplaydiv** [comment]
RpcError: {"codespace":"sdk","code":2,"message":"ERROR:\nCodespace: sdk\nCode: 2\nMessage: \"error decoding transaction: proto: illegal wireType 7\"\n"}
    at new RpcError (/Users/chainwang/projects/poktTest/node_modules/@pokt-network/pocket-js/dist/rpc/errors/rpc-error.js:52:28)
    at Function.RpcError.fromError (/Users/chainwang/projects/poktTest/node_modules/@pokt-network/pocket-js/dist/rpc/errors/rpc-error.js:67:16)
    at ClientNamespace.<anonymous> (/Users/chainwang/projects/poktTest/node_modules/@pokt-network/pocket-js/dist/rpc/namespaces/client.js:92:64)
    at step (/Users/chainwang/projects/poktTest/node_modules/@pokt-network/pocket-js/dist/rpc/namespaces/client.js:33:23)
    at Object.next (/Users/chainwang/projects/poktTest/node_modules/@pokt-network/pocket-js/dist/rpc/namespaces/client.js:14:53)
    at fulfilled (/Users/chainwang/projects/poktTest/node_modules/@pokt-network/pocket-js/dist/rpc/namespaces/client.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  code: '0',
  session: undefined,
  nodePubKey: undefined
}

**Comment by julycanfly** [comment]
Hi, I also encountered this problem, did you solve it

**Comment by kdasme** [comment]
This is an actual issue, the transaction hex generated by the pocket-js library is invalid.

**Comment by oten91** [comment]
Hello,
Please set this value to `false` so pocket-js uses protobuf instead of amino for sending tx bytes
https://github.com/pokt-network/pocket-js/blob/4560c4f27391ba72a7ffb2113b06e708b0f139c5/src/config/configuration.ts#L46

**Comment by kdasme** [comment]
@oten91 Thank you! Can confirm this resolves my issue.
